const city = [
    "Aceh",
    "Bali",
    "Balikpapan",
    "Bandung",
    "Banjarmasin",
    "Bekasi",
    "Bengkulu",
    "Bogor",
    "Cirebon",
    "Denpasar",
    "Jakarta",
    "Jayapura",
    "Kupang",
    "Makassar",
    "Malang",
    "Manado",
    "Mataram",
    "Medan",
    "Padang",
    "Palembang",
    "Palu",
    "Pekanbaru",
    "Pontianak",
    "Samarinda",
    "Semarang",
    "Surabaya",
    "Tangerang",
    "Yogyakarta",];

const timezone = {
    "Aceh": "Asia/Jakarta",
    "Bali": "Asia/Makassar",
    "Balikpapan": "Asia/Makassar",
    "Bandung": "Asia/Jakarta",
    "Banjarmasin": "Asia/Makassar",
    "Bekasi": "Asia/Jakarta",
    "Bengkulu": "Asia/Jakarta",
    "Bogor": "Asia/Jakarta",
    "Cirebon": "Asia/Jakarta",
    "Denpasar": "Asia/Makassar",
    "Jakarta": "Asia/Jakarta",
    "Jayapura": "Asia/Jayapura",
    "Kupang": "Asia/Makassar",
    "Makassar": "Asia/Makassar",
    "Malang": "Asia/Jakarta",
    "Manado": "Asia/Makassar",
    "Mataram": "Asia/Makassar",
    "Medan": "Asia/Jakarta",
    "Padang": "Asia/Jakarta",
    "Palembang": "Asia/Jakarta",
    "Palu": "Asia/Makassar",
    "Pekanbaru": "Asia/Jakarta",
    "Pontianak": "Asia/Pontianak",
    "Samarinda": "Asia/Makassar",
    "Semarang": "Asia/Jakarta",
    "Surabaya": "Asia/Jakarta",
    "Tangerang": "Asia/Jakarta",
    "Yogyakarta": "Asia/Jakarta",
  };